#! /bin/ksh --login

#PBS -e /scratch3/NCEPDEV/swpc/scrub/Robert.Oehmke/rt_25855/swpc%20130316_1hr_spacewx_gsm%wam%T62_ipe%80x170/err
#PBS -o /scratch3/NCEPDEV/swpc/scrub/Robert.Oehmke/rt_25855/swpc%20130316_1hr_spacewx_gsm%wam%T62_ipe%80x170/out
#PBS -N rt_25855_1
#PBS -A swpc
#PBS -q debug
#PBS -l procs=40
#PBS -l walltime=00:30:00
#PBS -W umask=027

if [[ -e  /scratch3/NCEPDEV/swpc/noscrub/Robert.Oehmke/bob_issue69/NEMS/src/conf/modules.nems ]]; then
  source /scratch3/NCEPDEV/swpc/noscrub/Robert.Oehmke/bob_issue69/NEMS/src/conf/modules.nems.sh
  module list
fi

set -aeux
export MPI_GROUP_MAX=96
# ulimit -n 16000
# Enable Fortran RTL core dumps for severe run time failures
# export decfort_dump_flag=y

export SCHEDULER=pbs

export FIXGLOBAL=/scratch4/NCEPDEV/nems/noscrub/emc.nemspara/RT/WAM-IPE/WAM-IPE_NEMS201606-20170302/data/GSM/fix_am

cd /scratch3/NCEPDEV/swpc/scrub/Robert.Oehmke/rt_25855/swpc%20130316_1hr_spacewx_gsm%wam%T62_ipe%80x170

echo "Model started:  " `date`

#module load intel
#module load mpt
#module load adaptive

export TASKSIZE=40

/scratch3/NCEPDEV/swpc/scrub/Robert.Oehmke/rt_25855/swpc%20130316_1hr_spacewx_gsm%wam%T62_ipe%80x170/gfs_fcst_run

echo "Model ended:    " `date`

exit
